import Nav from "@/components/marketing/Nav";
import Footer from "@/components/marketing/Footer";
import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = { title: "Public Beta", description: "Create a free Beckett beta account and test workplace communication coaching across connected work apps, Practice, and Skills.", alternates: { canonical: "/beta" } };
const perks = ["Immediate account creation—no invitation or approval wait", "60 successful coaching actions per day and 500 per month", "Google Workspace, Slack, Microsoft 365, Chrome, and Practice", "Every skill course currently available", "Course activities do not use coaching credits", "New capabilities clearly marked as they arrive during beta"];

export default function BetaPage() {
  return <main className="min-h-screen bg-bg"><Nav /><div className="mx-auto max-w-3xl px-4 pb-20 pt-32 sm:px-6"><div className="mb-12 text-center"><div className="mb-8 inline-flex items-center gap-2 rounded-pill bg-primary-light px-4 py-2 text-xs font-medium text-primary"><span className="inline-block h-2 w-2 animate-pulse rounded-full bg-primary" aria-hidden="true" />Public beta is open</div><h1 className="mb-5 text-4xl text-ink sm:text-5xl" style={{ fontFamily: "var(--font-dm-serif), Georgia, serif" }}>Use Beckett now. Help shape what comes next.</h1><p className="mx-auto max-w-2xl text-lg leading-relaxed text-ink-mid">We are opening Beckett to more beta testers who want clearer workplace communication support inside the apps they already use.</p></div><section className="mb-10 rounded-card border border-border bg-white p-8"><h2 className="mb-6 text-xl text-ink" style={{ fontFamily: "var(--font-dm-serif), Georgia, serif" }}>What you get</h2><ul className="mb-8 space-y-3">{perks.map((perk) => <li key={perk} className="flex items-start gap-3 text-sm text-ink-mid"><span className="text-primary" aria-hidden="true">✓</span><span>{perk}</span></li>)}</ul><Link href="/auth/signup" className="block rounded-pill bg-primary px-6 py-3 text-center text-sm font-medium text-white hover:bg-primary-dark">Create your free beta account</Link><p className="mt-3 text-center text-xs text-ink-light">No credit card required</p></section><p className="text-center text-sm text-ink-light">Already have an account? <Link href="/auth/login" className="text-primary hover:underline">Sign in</Link></p></div><Footer /></main>;
}
