import SafetyResourceRegionPicker from "@/components/dashboard/SafetyResourceRegionPicker";
import { allSafetyResources, getSafetyResourceRegionNotice, normalizeSafetyResourceRegion, safetyResourceRegionDetails } from "@/lib/safety-resources";
import { createSupabaseServerClient } from "@/lib/supabase-server";

export default async function SafetyPage() {
  const supabase = await createSupabaseServerClient();
  const { data: { user } } = await supabase.auth.getUser();
  const { data: profile } = user
    ? await supabase.from("profiles").select("safety_resource_region").eq("id", user.id).maybeSingle()
    : { data: null };
  const region = normalizeSafetyResourceRegion(profile?.safety_resource_region);
  const regionDetails = safetyResourceRegionDetails(region);
  const resources = allSafetyResources(region);
  return <div className="max-w-3xl"><h1 className="mb-2 text-3xl text-ink" style={{ fontFamily: "var(--font-dm-serif), Georgia, serif" }}>Support boundaries & resources</h1><p className="mb-7 text-sm text-ink-mid">Beckett is a communication coach. It cannot replace urgent, legal, medical, mental-health, or relationship-safety support.</p><SafetyResourceRegionPicker initialRegion={profile?.safety_resource_region} /><div className="mb-5 rounded-sm border border-primary/15 bg-primary-light/40 p-4 text-sm leading-relaxed text-ink-mid"><p>{getSafetyResourceRegionNotice(region)}</p><p className="mt-2 text-xs">Emergency routing for {regionDetails.label}: <span className="font-medium text-ink">{regionDetails.emergencyNumber}</span> · Resource language: {regionDetails.language}</p></div><div className="space-y-4">{resources.map((group) => <section key={group.topic} className="rounded-card border border-border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><h2 className="text-lg text-ink" style={{ fontFamily: "var(--font-dm-serif), Georgia, serif" }}>{group.title}</h2><span className={`rounded-pill px-2.5 py-1 text-[11px] font-medium ${group.reviewStatus === "current" ? "bg-green-50 text-green-700" : group.reviewStatus === "due" ? "bg-amber-50 text-amber-800" : "bg-red-50 text-red-700"}`}>{group.reviewStatus === "current" ? "Review current" : group.reviewStatus === "due" ? "Review due soon" : "Review overdue"}</span></div><p className="mt-2 text-sm leading-relaxed text-ink-mid">{group.message}</p><div className="mt-4 flex flex-col gap-2">{group.resources.map((resource) => <a key={resource.href} href={resource.href} target="_blank" rel="noreferrer" className="text-sm font-medium text-primary hover:underline">{resource.label} ↗</a>)}</div><p className="mt-4 text-xs leading-relaxed text-ink-light">{group.usingUSFallback ? "International fallback" : `${group.regionLabel} resource set`} · Source: {group.source} · Last reviewed {group.reviewedAt} · Next review {group.nextReviewAt} · Reviewed every {group.reviewCadenceDays} days · Owner: {group.owner}</p></section>)}</div><p className="mt-6 text-xs leading-relaxed text-ink-light">Resource availability and applicability vary by location. Beckett does not infer your precise location. If there is immediate danger, use the emergency number for your selected region or your local emergency services.</p></div>;
}
