import Nav from "@/components/marketing/Nav";
import Footer from "@/components/marketing/Footer";
import Link from "next/link";
import { CHROME_WEB_STORE_URL } from "@/lib/app-links";
import type { Metadata } from "next";

export const metadata: Metadata = { title: "Integrations", description: "Use Beckett across Google Workspace, Slack, Microsoft 365, and Chrome during public beta.", alternates: { canonical: "/integrations" } };

const integrations = [
  { name: "Google Workspace", icon: "G", description: "Analyze selected Gmail conversations and draft replies. Connect Google Calendar separately when you want read-only meeting preparation.", details: ["Gmail: optional", "Calendar: optional"] },
  { name: "Slack", icon: "S", description: "Get private decoding, response help, rewriting, preparation, and practice in channels, DMs, and threads.", details: ["Multiple workspaces", "/beckett command"] },
  { name: "Microsoft 365", icon: "M", description: "Analyze selected Outlook messages and use selected Microsoft calendars through one Microsoft authorization.", details: ["Outlook", "Microsoft Calendar"] },
  { name: "Beckett for Chrome", icon: "C", description: "Bring Beckett into supported browser tools and connect securely to your Beckett account.", details: ["Chrome Web Store"] },
];

export default function IntegrationsPage() {
  return <main className="min-h-screen bg-bg"><Nav /><div className="mx-auto max-w-6xl px-4 pb-20 pt-32 sm:px-6"><div className="mb-14 text-center"><p className="mb-3 text-xs font-medium uppercase tracking-wide text-primary">Connected work apps</p><h1 className="mb-4 text-4xl text-ink sm:text-5xl" style={{ fontFamily: "var(--font-dm-serif), Georgia, serif" }}>One Beckett, wherever the work happens</h1><p className="mx-auto max-w-2xl text-lg leading-relaxed text-ink-mid">Stay in the app where the conversation is happening. Connect only the capabilities you want and manage them from one Apps page.</p></div><section><div className="mb-5 flex items-center gap-3"><h2 className="text-2xl text-ink" style={{ fontFamily: "var(--font-dm-serif), Georgia, serif" }}>Available during beta</h2><span className="rounded-pill bg-green-50 px-3 py-1 text-xs font-medium text-green-700">Live</span></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{integrations.map((item) => <article key={item.name} className="flex flex-col rounded-card border border-border bg-white p-6"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-primary-light font-semibold text-primary" aria-hidden="true">{item.icon}</div><h3 className="mt-4 text-lg text-ink" style={{ fontFamily: "var(--font-dm-serif), Georgia, serif" }}>{item.name}</h3><p className="mt-2 flex-1 text-sm leading-relaxed text-ink-mid">{item.description}</p><div className="mt-4 flex flex-wrap gap-2">{item.details.map((detail) => <span key={detail} className="rounded-pill border border-border bg-bg px-2.5 py-1 text-xs text-ink-light">{detail}</span>)}</div>{item.name === "Beckett for Chrome" && <Link href={CHROME_WEB_STORE_URL} target="_blank" rel="noreferrer" className="mt-4 text-xs font-medium text-primary hover:underline">Install from Chrome Web Store →</Link>}</article>)}</div></section><section className="mt-14 rounded-card border border-dashed border-border bg-white/70 p-7"><p className="text-xs font-medium uppercase tracking-wide text-primary">Coming during beta</p><h2 className="mt-1 text-2xl text-ink" style={{ fontFamily: "var(--font-dm-serif), Georgia, serif" }}>More connected workflows</h2><p className="mt-2 text-sm text-ink-mid">Additional integrations and deeper calendar capabilities will appear here only when they are ready for beta testing.</p></section><div className="mt-14 text-center"><Link href="/auth/signup" className="inline-block rounded-pill bg-primary px-8 py-3 text-sm font-medium text-white hover:bg-primary-dark">Create your free beta account</Link></div></div><Footer /></main>;
}
