import Nav from "@/components/marketing/Nav";
import Footer from "@/components/marketing/Footer";
import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = { title: "Features", description: "Beckett brings workplace communication coaching into Gmail, Slack, Outlook, Calendar, Chrome, and realistic Practice.", alternates: { canonical: "/features" } };

const available = [
  { title: "Google Workspace", icon: "G", description: "Analyze selected Gmail conversations, draft editable replies, and separately connect selected Google calendars for meeting preparation." },
  { title: "Slack", icon: "S", description: "Decode messages, draft or rewrite replies, prepare, and practice privately inside Slack." },
  { title: "Microsoft 365", icon: "M", description: "Work with selected Outlook messages and Microsoft calendars through one Microsoft authorization." },
  { title: "Beckett for Chrome", icon: "C", description: "Open coaching from supported pages in your browser without rebuilding the context in a separate tool." },
  { title: "Conversation Practice", icon: "P", description: "Rehearse a real workplace conversation with realistic responses, then review what worked and what to try next." },
  { title: "Message decoder and reply drafting", icon: "D", description: "Separate observable meaning from uncertain tone, compare response approaches, and choose wording that sounds like you." },
  { title: "Home and meeting preparation", icon: "H", description: "See the shape of your day, check in, and prepare for meetings using only the calendars you choose." },
  { title: "About Me, Contacts, and support plans", icon: "A", description: "Give Beckett the communication preferences and relationship context you want it to use across coaching." },
  { title: "Skill courses", icon: "K", description: "Work through currently available courses on introductions and asking for clarity, with more arriving during beta." },
];
const coming = ["Additional workplace skill courses", "Deeper calendar planning", "More connected work apps"];

export default function FeaturesPage() {
  return <main className="min-h-screen bg-bg"><Nav /><div className="mx-auto max-w-6xl px-4 pb-20 pt-32 sm:px-6"><div className="mb-14 text-center"><p className="mb-3 text-xs font-medium uppercase tracking-wide text-primary">One coach across your workday</p><h1 className="mb-4 text-4xl text-ink sm:text-5xl" style={{ fontFamily: "var(--font-dm-serif), Georgia, serif" }}>Support where the conversation already lives</h1><p className="mx-auto max-w-2xl text-lg leading-relaxed text-ink-mid">Use Beckett inside the work apps you already have, then open the web app when you want deeper preparation, practice, or skill-building.</p></div><section><div className="mb-5 flex items-center gap-3"><h2 className="text-2xl text-ink" style={{ fontFamily: "var(--font-dm-serif), Georgia, serif" }}>Available in beta</h2><span className="rounded-pill bg-green-50 px-3 py-1 text-xs font-medium text-green-700">Live</span></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{available.map((feature) => <article key={feature.title} className="rounded-card border border-border bg-white p-6"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-primary-light font-semibold text-primary" aria-hidden="true">{feature.icon}</div><h3 className="mt-4 text-lg text-ink" style={{ fontFamily: "var(--font-dm-serif), Georgia, serif" }}>{feature.title}</h3><p className="mt-2 text-sm leading-relaxed text-ink-mid">{feature.description}</p></article>)}</div></section><section className="mt-14 rounded-card border border-dashed border-border bg-white/70 p-7"><p className="text-xs font-medium uppercase tracking-wide text-primary">Coming during beta</p><h2 className="mt-1 text-2xl text-ink" style={{ fontFamily: "var(--font-dm-serif), Georgia, serif" }}>The connected experience will keep growing</h2><div className="mt-5 flex flex-wrap gap-3">{coming.map((item) => <span key={item} className="rounded-pill border border-border bg-bg px-4 py-2 text-sm text-ink-mid">{item}</span>)}</div></section><div className="mt-14 rounded-card border border-primary/20 bg-primary-light p-8 text-center"><h2 className="text-2xl text-ink" style={{ fontFamily: "var(--font-dm-serif), Georgia, serif" }}>Try the complete beta</h2><p className="mx-auto mt-2 max-w-xl text-sm text-ink-mid">Accounts are created immediately. No invitation or approval wait is required.</p><Link href="/auth/signup" className="mt-6 inline-block rounded-pill bg-primary px-6 py-3 text-sm font-medium text-white hover:bg-primary-dark">Create your free account</Link></div></div><Footer /></main>;
}
